export function generateMarkdownReport(scenario, activeTimeWindow = 'Current') {
  const dateStr = new Date().toLocaleString();

  return `# REALITY INTELLIGENCE REPORT
**Generated by Reality Search Engine AI**
**Timestamp:** ${dateStr}
**Query:** "${scenario.query}"
**Classification Intent:** ${scenario.intent} (Confidence: ${(scenario.confidence * 100).toFixed(1)}%)
**Time Window:** ${activeTimeWindow}

---

## 1. EXECUTIVE SUMMARY
${scenario.predictionSummary}

### Key Metrics
- **Total Entities Identified:** ${scenario.summaryStats.totalFound}
- **High Risk / Inundated:** ${scenario.summaryStats.highRisk}
- **Affected:** ${scenario.summaryStats.affected}
- **Safe / Operational:** ${scenario.summaryStats.safe}
- **Predicted Risk (+6h):** +${scenario.summaryStats.predictedRiskIn6h} entities
- **Exposed Population / Sector:** ${scenario.summaryStats.populationExposed}
- **Road Accessibility Index:** ${scenario.summaryStats.roadAccessibility}

---

## 2. REALITY QUERY BREAKDOWN
- **Entity Type:** ${scenario.extractedTokens.entity}
- **Target Event:** ${scenario.extractedTokens.event}
- **Geospatial Scope:** ${scenario.extractedTokens.location}
- **Relationship Graph:** ${scenario.extractedTokens.relationship}

---

## 3. CRITICAL ENTITY STATUS TABLE

| Entity Name | District | Status | Severity | Accessibility / Condition | Water/Risk Level |
| ----------- | -------- | ------ | -------- | ------------------------- | ---------------- |
${scenario.entities.map(e => `| ${e.name} | ${e.district} | ${e.status} | ${e.severity} | ${e.roadAccess} | ${e.waterLevel} |`).join('\n')}

---

## 4. MULTI-SOURCE EVIDENCE VERIFICATION

${scenario.evidence.map(ev => `### 🌐 ${ev.sourceType}: ${ev.title}
- **Verified By:** ${ev.verifiedBy} (Confidence: ${ev.confidence})
- **Timestamp:** ${ev.timestamp}
- **Finding:** "${ev.snippet}"
`).join('\n')}

---

## 5. RECOMMENDED EMERGENCY ACTIONS
1. Dispatch amphibious rescue vehicles and motorboats to high-risk hospitals in Dindigul & Madurai.
2. Establish continuous emergency power fuel resupply to generators with < 4h operational capacity.
3. Reroute logistics convoy via open Highway corridors highlighted on the Reality GIS Map.
4. Notify district collectors for pre-emptive evacuation in +6h predicted risk zones.

---
*Report ID: RSE-${Math.floor(100000 + Math.random() * 900000)} | Reality Search Engine Platform*
`;
}
